function params = packwelldetectparm(app)
    params.Algo = app.AlgorithmDropDown.Value;
    params.Minitbins = app.MinitbinswidthmEditField.Value;
    params.Stepitbins = app.StepitbinswidthmEditField.Value;
    params.Maxitbins = app.MaxitbinswidthmEditField.Value;
    params.Densitybins = app.DensitybinswidthmEditField.Value;
    params.ThreeDbins = app.DbinnumberEditField.Value;
    params.Densityfit = app.DensityfitDropDown.Value;
    params.Densitythresh = app.DensitythresholdEditField.Value;
    params.Minseeddist = app.MinseeddistancecellsEditField.Value;
    params.Maxwellarea = app.MaxwellareamEditField.Value;
    params.Minwellpts = app.MinwellptsEditField.Value;
    params.Confidencell = app.ConfidenceellipsispercentDropDown.Value;
    params.Bestitshift = app.BestitshiftEditField.Value;
    params.Estimator = app.EstimatorDropDown.Value;
    params.Iterationscore = app.IterationscoringDropDown.Value;
    params.Maxlinkdist = app.MaxlinkingdistancemEditField.Value;
    params.Maxwin = app.MaxwindowsgapEditField.Value;
end
